@startuml 6
class クラス
class 生徒
class 担任 {
    役職: 担任
}
class 副担任 {
    役職: 副担任
}
class 教員
class 役職

クラス " 1" o-- "1..35" 生徒
クラス "1" o-- "1" 担任
クラス "*" o-- "1..2   " 副担任

担任 --|> 教員
副担任 --|> 教員

教員 "*" -- "0..1" 役職

@enduml
