@startuml 6
class ユーザー
class 一般ユーザー
class 職員


class コミュニティホール
class 施設
class 会議室
class 大会議室
class 小ホール

会議室 <|-- 施設
大会議室 <|-- 施設
小ホール <|-- 施設

ユーザー <|-- 一般ユーザー
ユーザー <|-- 職員


class 予約

コミュニティホール "1" o-- "6" 会議室
コミュニティホール "1" o-- "2" 大会議室
コミュニティホール "1" o-- "1" 小ホール

施設 "1" <-down- "1" 予約
予約 "1" -right-> "1" 一般ユーザー

@enduml
