@startuml sub6
left to right direction
actor 職員
actor IDあり一般ユーザー
actor IDなし一般ユーザー
rectangle 予約システム {
  usecase 空き状況確認
  usecase ユーザー認証
  usecase 予約情報登録
  usecase 予約状況確認
  usecase 予約キャンセル
  usecase 予約情報修正
  usecase ユーザー情報登録
  usecase ユーザー情報編集
  usecase ユーザー情報削除
  usecase ユーザーパスワード再設定
}
IDなし一般ユーザー --> 空き状況確認
IDあり一般ユーザー --> 空き状況確認
IDあり一般ユーザー --> ユーザー認証
IDあり一般ユーザー --> 予約情報登録
IDあり一般ユーザー --> 予約状況確認
IDあり一般ユーザー --> 予約キャンセル
空き状況確認 <-- 職員
予約状況確認 <-- 職員
予約情報登録 <-- 職員
予約キャンセル <-- 職員
予約情報修正 <-- 職員
ユーザー情報登録 <-- 職員
ユーザー認証 <-- 職員
ユーザー情報編集 <-- 職員
ユーザー情報削除 <-- 職員
ユーザーパスワード再設定 <-- 職員

@enduml
